In [120]:
import numpy as np
import math
# 这个classify ，你输入数据每个数据的权重，需要输出新学习器的预测（以及学习器训练出的参数，视具体情况），然后返回新学习器的误差，alpha以及对权重的的更新
def classify(data,weight):
    y=data[:,1]
    x=data[:,0] # 在实际应用中你得用其他的数据导入方式
    
    error=10000000
    for i in np.arange(0,len(x)): 
        y_predict=np.array([1 if k<x[i] else -1 for k in x])
        # now we compare y_predict and y. we want to find out the samples that are mistakenly classified.
        err=np.sum(weight[np.where(y_predict!=y) ]) # the error 
        if (err<error):
            error=err
            threshold_final=x[i]
            mistake_final=np.where(y_predict!=y)
            y_predict_final=y_predict
    
    for i in np.arange(0,len(x)): 
        y_predict=np.array([1 if k>x[i] else -1 for k in x])
        # now we compare y_predict and y. we want to find out the samples that are mistakenly classified.
        err=np.sum(weight[np.where(y_predict!=y) ]) # the error 
        if (err<error):
            error=err
            threshold_final=x[i]
            mistake_final=np.where(y_predict!=y)
            y_predict_final=y_predict
    # in reality, the above is a large classifier. you need mistake_final, y_predict_final,error
   # 从error=1000000到上面那一行都是我的自己定义的一个学习器，在实际应用中你应该插入其他的。。但是你都需要返回模型的误差，预测
    alpha=0.5*math.log((1-error)/error) 
    weight_new=np.array([weight[k]*math.exp(-alpha*y[k]*y_predict_final[k]) for k in np.arange(0,len(x)) ])
    weight_new=weight_new/np.sum(weight_new)
    # you want to return y_predict, weight_new , alpha,
    return y_predict_final, weight_new, alpha,error,threshold_final  # 这里的threshold_final 代表的是模型参数，实践中注意换成其他
        

In [121]:
# The next is just for a test.
weight=np.ones(10)*0.1
np.shape(weight)
y=np.array([1,1,1,-1,-1,-1,1,1,1,-1])
x=np.arange(0,10)
c=np.stack((x,y)) # 可以把向量叠起来
d=c.transpose() # 但是需要一下转置
current_predict=np.zeros(10)
s=1 
while s<=3: # We assume that we only iterate up to 3 basic classifier
    y_predict_new,weight_new,alpha_new,wucha,threshold_final=classify(d,weight)
    print(wucha) 
    weight=weight_new
    current_predict=current_predict+alpha_new*y_predict_new
    s=s+1
    

[0.07142857 0.07142857 0.07142857 0.07142857 0.07142857 0.07142857
 0.16666667 0.16666667 0.16666667 0.07142857]
0.4236489301936017
0.30000000000000004
3
[ 1  1  1 -1 -1 -1 -1 -1 -1 -1]
[0.04545455 0.04545455 0.04545455 0.16666667 0.16666667 0.16666667
 0.10606061 0.10606061 0.10606061 0.04545455]
0.6496414920651304
0.21428571428571427
9
[ 1  1  1  1  1  1  1  1  1 -1]
[0.125      0.125      0.125      0.10185185 0.10185185 0.10185185
 0.06481481 0.06481481 0.06481481 0.125     ]
0.752038698388137
0.18181818181818185
5
[-1 -1 -1 -1 -1 -1  1  1  1  1]
